### ISSUE TITLE
你好 perdict 没有计算acc recall f1score等问题

### ISSUE THREAD

**Issue by jielunzhou18754** [Xuanfang1121/relation-extract-tplinker-ch#2]
你好我知道dule2.0数据集test没有答案三元组，所以我将val的数据随机拆分成2份 一份作为val 一份作为 test但是这样perdict并没有写acc recall 和f1值的计算问题您能给个思路解决acc recall 和f1值的解决问题吗

**Comment by Xuanfang1121** [comment]
predict用来模型推理的，直接得到模型抽取的三元组结果，计算acc， recall， precision以及f1 score 是用来模型评价的，参考main.py中的模型验证这部分的代码修改可以得到
