### ISSUE TITLE
可以分享下数据集吗

### ISSUE THREAD

**Issue by lelegogo26** [Xuanfang1121/relation-extract-tplinker-ch#4]

**Comment by Xuanfang1121** [comment]
可以发一下邮箱吗

**Comment by Xuanfang1121** [comment]
> _No description provided._
可以发一下邮箱吗

**Comment by lelegogo26** [comment]
***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月18日(周二) 下午5:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xuanfang1121/relation-extract-tplinker-ch] 可以分享下数据集吗 (Issue #4)




 
可以发一下邮箱吗
